version: '3.8'
services:
  frontend:
    build:
      context: ./freeflix-react
    container_name: freeflix-frontend
    volumes:
      - frontend_build:/app/build
  backend:
    build: .
    container_name: freeflix-backend
    volumes:
      - ${MEDIA_ROOT}:/app/media
    env_file:
      - .prod.env
    expose:
      - 8000
  node_backend:
    build:
      context: ./node-media-server
    container_name: freeflix-node-backend
    volumes:
      - ${MEDIA_ROOT}:/app/media
    environment:
      - PORT=8080
      - DJANGO_URL_PATH=http://backend:8000
    expose:
      - 8080
  web_server:
    image: nginx
    container_name: freelix-nginx-container
    volumes:
      - ${MEDIA_ROOT}:/usr/share/nginx/media
      - ./nginx-server/config.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    ports:
      - 80:80

volumes:
  frontend_build: